exports.sentenceFormulas = [
  {
    key: "SF-00001",
    equivalents: { ENG: ["ENG-default"], POL: [], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00002",
    equivalents: { ENG: ["ENG-101a"], POL: ["POL-101a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00003",
    equivalents: { ENG: ["ENG-101b"], POL: ["POL-101b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00004",
    equivalents: { ENG: ["ENG-102a"], POL: ["POL-102a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00005",
    equivalents: { ENG: ["ENG-103a"], POL: ["POL-103a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00006",
    equivalents: { ENG: ["ENG-103b"], POL: ["POL-103b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00007",
    equivalents: { ENG: ["ENG-103c"], POL: ["POL-103c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00008",
    equivalents: { ENG: ["ENG-104a"], POL: ["POL-104a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00009",
    equivalents: { ENG: ["ENG-104b"], POL: ["POL-104b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00010",
    equivalents: { ENG: ["ENG-105a"], POL: ["POL-105a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00011",
    equivalents: { ENG: ["ENG-106a"], POL: ["POL-106a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00012",
    equivalents: { ENG: ["ENG-107"], POL: ["POL-107"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00013",
    equivalents: { ENG: ["ENG-107a"], POL: ["POL-107"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00014",
    equivalents: { ENG: ["ENG-108"], POL: ["POL-108"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00015",
    equivalents: { ENG: ["ENG-109"], POL: ["POL-109"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00016",
    equivalents: { ENG: ["ENG-109a"], POL: ["POL-109a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00017",
    equivalents: { ENG: ["ENG-109b"], POL: ["POL-109b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00018",
    equivalents: { ENG: ["ENG-109c"], POL: ["POL-109c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00019",
    equivalents: { ENG: ["ENG-110"], POL: ["POL-110"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00020",
    equivalents: { ENG: ["ENG-111a"], POL: ["POL-111a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00021",
    equivalents: { ENG: ["ENG-111b"], POL: ["POL-111b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00022",
    equivalents: { ENG: ["ENG-111c"], POL: ["POL-111c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00023",
    equivalents: { ENG: ["ENG-112"], POL: ["POL-112"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00024",
    equivalents: { ENG: ["ENG-112a"], POL: ["POL-112a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00025",
    equivalents: { ENG: ["ENG-113"], POL: ["POL-113"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00026",
    equivalents: { ENG: ["ENG-113a"], POL: ["POL-113a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00027",
    equivalents: { ENG: ["ENG-113b"], POL: ["POL-113b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00028",
    equivalents: { ENG: ["ENG-113c"], POL: ["POL-113c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00029",
    equivalents: { ENG: ["ENG-114"], POL: ["POL-114"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00030",
    equivalents: { ENG: ["ENG-115"], POL: ["POL-115"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00031",
    equivalents: { ENG: ["ENG-116b"], POL: ["POL-116b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00032",
    equivalents: { ENG: ["ENG-116c"], POL: ["POL-116c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00033",
    equivalents: { ENG: ["ENG-116y"], POL: ["POL-116y"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00034",
    equivalents: { ENG: ["ENG-116x"], POL: ["POL-116x"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00035",
    equivalents: { ENG: ["ENG-116a"], POL: ["POL-116a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00036",
    equivalents: { ENG: ["ENG-117"], POL: ["POL-117"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00037",
    equivalents: { ENG: ["ENG-117a"], POL: ["POL-117a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00038",
    equivalents: { ENG: ["ENG-117aa"], POL: ["POL-117aa"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00039",
    equivalents: { ENG: ["ENG-117b"], POL: ["POL-117b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00040",
    equivalents: { ENG: ["ENG-117c"], POL: ["POL-117c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00041",
    equivalents: { ENG: ["ENG-118"], POL: ["POL-118"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00042",
    equivalents: { ENG: ["ENG-118a"], POL: ["POL-118a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00043",
    equivalents: { ENG: ["ENG-118b"], POL: ["POL-118b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00044",
    equivalents: { ENG: ["ENG-118c"], POL: ["POL-118c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00045",
    equivalents: { ENG: ["ENG-119"], POL: ["POL-119"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00046",
    equivalents: { ENG: ["ENG-120"], POL: ["POL-120"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00047",
    equivalents: { ENG: ["ENG-121"], POL: ["POL-121"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00048",
    equivalents: { ENG: ["ENG-122"], POL: ["POL-122"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00049",
    equivalents: { ENG: ["ENG-123"], POL: ["POL-123"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00050",
    equivalents: { ENG: ["ENG-124a"], POL: ["POL-124a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00051",
    equivalents: { ENG: ["ENG-124b"], POL: ["POL-124b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00052",
    equivalents: { ENG: ["ENG-124c"], POL: ["POL-124c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00053",
    equivalents: { ENG: ["ENG-101c"], POL: ["POL-101c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00054",
    equivalents: { ENG: ["ENG-123aa"], POL: ["POL-123aa"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00055",
    equivalents: {
      ENG: ["ENG-123ab", "ENG-123da", "ENG-123db"],
      POL: ["POL-123ab"],
      SPA: [],
    },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00056",
    equivalents: { ENG: ["ENG-123ba"], POL: ["POL-123ba"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00057",
    equivalents: { ENG: ["ENG-123baa"], POL: ["POL-123baa"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00058",
    equivalents: {
      ENG: ["ENG-123bb", "ENG-123ea", "ENG-123eb"],
      POL: ["POL-123bb"],
      SPA: [],
    },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00059",
    equivalents: { ENG: ["ENG-123ca"], POL: ["POL-123ca"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00060",
    equivalents: { ENG: ["ENG-123caa"], POL: ["POL-123caa"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00061",
    equivalents: {
      ENG: ["ENG-123cb", "ENG-123fa", "ENG-123fb"],
      POL: ["POL-123cb"],
      SPA: [],
    },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00062",
    equivalents: { ENG: ["ENG-123aaa"], POL: ["POL-123aaa"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00063",
    equivalents: { ENG: ["ENG-123g"], POL: ["POL-123g"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00064",
    equivalents: { ENG: ["ENG-123h"], POL: ["POL-123h"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00065",
    equivalents: { ENG: ["ENG-125a"], POL: ["POL-125a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00066",
    equivalents: { ENG: ["ENG-125b"], POL: ["POL-125b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00067",
    equivalents: { ENG: ["ENG-125c"], POL: ["POL-125c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-00068",
    equivalents: { ENG: ["ENG-127a"], POL: ["POL-127a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
];
