exports.sentenceFormulas = [
  {
    key: "SF-0001",
    equivalents: { ENG: ["ENG-default"], POL: [], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0002",
    equivalents: { ENG: ["ENG-101a"], POL: ["POL-101a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0003",
    equivalents: { ENG: ["ENG-101b"], POL: ["POL-101b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0004",
    equivalents: { ENG: ["ENG-102a"], POL: ["POL-102a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0005",
    equivalents: { ENG: ["ENG-103a"], POL: ["POL-103a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0006",
    equivalents: { ENG: ["ENG-103b"], POL: ["POL-103b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0007",
    equivalents: { ENG: ["ENG-103c"], POL: ["POL-103c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0008",
    equivalents: { ENG: ["ENG-104a"], POL: ["POL-104a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0009",
    equivalents: { ENG: ["ENG-104b"], POL: ["POL-104b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0010",
    equivalents: { ENG: ["ENG-105a"], POL: ["POL-105a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0011",
    equivalents: { ENG: ["ENG-106a"], POL: ["POL-106a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0012",
    equivalents: { ENG: ["ENG-107"], POL: ["POL-107"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0013",
    equivalents: { ENG: ["ENG-107a"], POL: ["POL-107"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0014",
    equivalents: { ENG: ["ENG-108"], POL: ["POL-108"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0015",
    equivalents: { ENG: ["ENG-109"], POL: ["POL-109"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0016",
    equivalents: { ENG: ["ENG-109a"], POL: ["POL-109a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0017",
    equivalents: { ENG: ["ENG-109b"], POL: ["POL-109b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0018",
    equivalents: { ENG: ["ENG-109c"], POL: ["POL-109c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0019",
    equivalents: { ENG: ["ENG-110"], POL: ["POL-110"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0020",
    equivalents: { ENG: ["ENG-111a"], POL: ["POL-111a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0021",
    equivalents: { ENG: ["ENG-111b"], POL: ["POL-111b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0022",
    equivalents: { ENG: ["ENG-111c"], POL: ["POL-111c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0023",
    equivalents: { ENG: ["ENG-112"], POL: ["POL-112"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0024",
    equivalents: { ENG: ["ENG-112a"], POL: ["POL-112a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0025",
    equivalents: { ENG: ["ENG-113"], POL: ["POL-113"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0026",
    equivalents: { ENG: ["ENG-113a"], POL: ["POL-113a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0027",
    equivalents: { ENG: ["ENG-113b"], POL: ["POL-113b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0028",
    equivalents: { ENG: ["ENG-113c"], POL: ["POL-113c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0029",
    equivalents: { ENG: ["ENG-114"], POL: ["POL-114"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0030",
    equivalents: { ENG: ["ENG-115"], POL: ["POL-115"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0031",
    equivalents: { ENG: ["ENG-116b"], POL: ["POL-116b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0032",
    equivalents: { ENG: ["ENG-116c"], POL: ["POL-116c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0033",
    equivalents: { ENG: ["ENG-116y"], POL: ["POL-116y"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0034",
    equivalents: { ENG: ["ENG-116x"], POL: ["POL-116x"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0035",
    equivalents: { ENG: ["ENG-116a"], POL: ["POL-116a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0036",
    equivalents: { ENG: ["ENG-117"], POL: ["POL-117"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0037",
    equivalents: { ENG: ["ENG-117a"], POL: ["POL-117a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0038",
    equivalents: { ENG: ["ENG-117aa"], POL: ["POL-117aa"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0039",
    equivalents: { ENG: ["ENG-117b"], POL: ["POL-117b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0040",
    equivalents: { ENG: ["ENG-117c"], POL: ["POL-117c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0041",
    equivalents: { ENG: ["ENG-118"], POL: ["POL-118"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0042",
    equivalents: { ENG: ["ENG-118a"], POL: ["POL-118a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0043",
    equivalents: { ENG: ["ENG-118b"], POL: ["POL-118b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0044",
    equivalents: { ENG: ["ENG-118c"], POL: ["POL-118c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0045",
    equivalents: { ENG: ["ENG-119"], POL: ["POL-119"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0046",
    equivalents: { ENG: ["ENG-120"], POL: ["POL-120"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0047",
    equivalents: { ENG: ["ENG-121"], POL: ["POL-121"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0048",
    equivalents: { ENG: ["ENG-122"], POL: ["POL-122"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0049",
    equivalents: { ENG: ["ENG-123"], POL: ["POL-123"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0050",
    equivalents: { ENG: ["ENG-124a"], POL: ["POL-124a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0051",
    equivalents: { ENG: ["ENG-124b"], POL: ["POL-124b"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0052",
    equivalents: { ENG: ["ENG-124c"], POL: ["POL-124c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0053",
    equivalents: { ENG: ["ENG-101c"], POL: ["POL-101c"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
  {
    key: "SF-0054",
    equivalents: { ENG: ["ENG-123a"], POL: ["POL-123a"], SPA: [] },
    topics: [],
    difficulty: 0,
  },
];
