exports.egSentences = {
  dummy01: [
    {
      type: "noun",
      manTags: ["nonexistent tag"],
      optTags: [],
      gcase: ["nom"],
      number: ["singular"],
      gender: [],
    },
    "must surely be impossible",
  ],
  dummy02: [
    {
      type: "noun",
      manTags: [],
      optTags: [],
      gcase: ["nonexistent gcase"],
      number: [],
      gender: [],
    },
    "must surely be impossible",
  ],
  dummy03: [
    {
      type: "noun",
      manTags: ["dummy"],
      optTags: [],
      gcase: ["nom"],
      number: [],
      gender: [],
    },
    "must be impossible when using dummy noun",
  ],
  dummy04: [
    {
      type: "noun",
      manTags: ["dummy"],
      optTags: [],
      gcase: ["nom"],
      number: ["singular", "plural"],
      gender: [],
    },
    "must be impossible when using dummy noun",
  ],
  dummy05: [
    {
      type: "noun",
      manTags: ["dummy"],
      optTags: [],
      gcase: ["nom", "loc"],
      number: [],
      gender: [],
    },
    "should be possible even using dummy noun",
  ],
  50: [
    {
      type: "noun",
      manTags: ["person"],
      optTags: [],
      gcase: ["nom"],
      number: ["singular"],
      gender: [],
    },
    "je",
    {
      type: "noun",
      manTags: ["edible"],
      optTags: [],
      gcase: ["acc"],
      number: [],
      gender: [],
    },
  ],
  51: [
    {
      type: "noun",
      manTags: ["person"],
      optTags: [],
      gcase: ["nom"],
      number: ["singular"],
      gender: [],
    },
    "ma na sobie",
    {
      type: "noun",
      manTags: ["wearable"],
      optTags: [],
      gcase: ["acc"],
      number: [],
      gender: [],
    },
  ],
  52: [
    {
      type: "noun",
      manTags: ["wearable"],
      optTags: [],
      gcase: ["nom"],
      number: ["singular"],
      gender: [],
    },
    "jest w szafie",
  ],
  53: [
    "Często noszę",
    {
      type: "noun",
      manTags: ["wearable"],
      optTags: [],
      gcase: ["acc"],
      number: ["singular", "plural"],
      gender: [],
    },
  ],
};
