let nounSet = [
  {
    translations: { EN: ["woman", "lady"] },
    lemma: "kobieta",
    id: "pl-nou-001",
    gender: "f",
    tags: ["animate", "person", "concrete"],
    defective: false,
    inflections: {
      singular: {
        nom: "kobieta",
        gen: "kobiety",
        dat: "kobiecie",
        acc: "kobietę",
        ins: "kobietą",
        loc: "kobiecie",
      },
      plural: {
        nom: "kobiety",
        gen: "kobiet",
        dat: "kobietom",
        acc: "kobiety",
        ins: "kobietami",
        loc: "kobietach",
      },
    },
  },
  {
    translations: { EN: ["boy", "boyfriend", "guy"] },
    lemma: "chłopak",
    id: "pl-nou-002",
    gender: "m1",
    tags: ["animate", "person", "concrete"],
    defective: false,
    inflections: {
      singular: {
        nom: "chłopak",
        gen: "chłopaka",
        dat: "chłopakowi",
        acc: "chłopaka",
        ins: "chłopakiem",
        loc: "chłopaku",
      },
      plural: {
        nom: ["chłopacy", "chłopaki"],
        gen: "chłopaków",
        dat: "chłopakom",
        acc: "chłopaków",
        ins: "chłopakami",
        loc: "chłopakach",
      },
    },
  },
  {
    translations: { EN: ["boy", "little boy"] },
    lemma: "chłopiec",
    id: "pl-nou-003",
    gender: "m1",
    tags: ["animate", "person", "concrete"],
    defective: false,
    inflections: {
      singular: {
        nom: "chłopiec",
        gen: "chłopca",
        dat: "chłopcu",
        acc: "chłopca",
        ins: "chłopcem",
        loc: "chłopcu",
      },
      plural: {
        nom: "chłopcy",
        gen: "chłopców",
        dat: "chłopcom",
        acc: "chłopców",
        ins: "chłopcami",
        loc: "chłopcach",
      },
    },
  },
  {
    translations: { EN: ["onion"] },
    lemma: "cebula",
    id: "pl-nou-004",
    gender: "f",
    tags: ["inanimate", "edible", "holdable", "concrete"],
    defective: false,
    inflections: {
      singular: {
        nom: "cebula",
        gen: "cebuli",
        dat: "cebuli",
        acc: "cebulę",
        ins: "cebulą",
        loc: "cebuli",
      },
      plural: {
        nom: "cebule",
        gen: "cebul",
        dat: "cebulom",
        acc: "cebule",
        ins: "cebulami",
        loc: "cebulach",
      },
    },
  },
  {
    translations: { EN: ["apple"] },
    lemma: "jabłko",
    id: "pl-nou-005",
    gender: "n",
    tags: ["inanimate", "edible", "holdable", "concrete"],
    defective: false,
    inflections: {
      singular: {
        nom: "jabłko",
        gen: "jabłka",
        dat: "jabłku",
        acc: "jabłko",
        ins: "jabłkiem",
        loc: "jabłku",
      },
      plural: {
        nom: "jabłka",
        gen: "jabłek",
        dat: "jabłkom",
        acc: "jabłka",
        ins: "jabłkami",
        loc: "jabłkach",
      },
    },
  },
  {
    translations: { EN: ["mirror"] },
    lemma: "lustro",
    id: "pl-nou-006",
    gender: "n",
    tags: ["inanimate", "holdable", "concrete"],
    defective: false,
    inflections: {
      singular: {
        nom: "lustro",
        gen: "lustra",
        dat: "lustru",
        acc: "lustro",
        ins: "lustrem",
        loc: "lustrze",
      },
      plural: {
        nom: "lustra",
        gen: "luster",
        dat: "lustrom",
        acc: "lustra",
        ins: "lustrami",
        loc: "lustrach",
      },
    },
  },
  {
    translations: { EN: ["mirror"] },
    lemma: "zwierciadło",
    id: "pl-nou-007",
    gender: "n",
    tags: ["inanimate", "holdable", "concrete"],
    defective: false,
    inflections: {
      singular: {
        nom: "zwierciadło",
        gen: "zwierciadła",
        dat: "zwierciadłu",
        acc: "zwierciadło",
        ins: "zwierciadłem",
        loc: "zwierciadle",
      },
      plural: {
        nom: "zwierciadła",
        gen: "zwierciadeł",
        dat: "zwierciadłom",
        acc: "zwierciadła",
        ins: "zwierciadłami",
        loc: "zwierciadłach",
      },
    },
  },
  {
    translations: {
      EN: ["underwear", "pants", "underpants", "briefs", "panties"],
    },
    lemma: "majtki",
    id: "pl-nou-008",
    gender: "f",
    tags: ["inanimate", "holdable", "concrete", "wearable"],
    defective: true,
    inflections: {
      plural: {
        nom: "majtki",
        gen: "majtek",
        dat: "majtkom",
        acc: "majtki",
        ins: "majtkami",
        loc: "majtkach",
      },
    },
  },
];
let adjectiveSet = [
  {
    translations: { EN: ["red"] },
    lemma: "czerwony",
    id: "pl-adj-001",
    tags: ["colour"],
    defective: false,
    inflections: {
      singular: {
        m1: {
          nom: "czerwony",
          gen: "czerwonego",
          dat: "czerwonemu",
          acc: "czerwonego",
          ins: "czerwonym",
          loc: "czerwonym",
        },
        m2: {
          nom: "czerwony",
          gen: "czerwonego",
          dat: "czerwonemu",
          acc: "czerwonego",
          ins: "czerwonym",
          loc: "czerwonym",
        },
        m3: {
          nom: "czerwony",
          gen: "czerwonego",
          dat: "czerwonemu",
          acc: "czerwony",
          ins: "czerwonym",
          loc: "czerwonym",
        },
        n: {
          nom: "czerwone",
          gen: "czerwonego",
          dat: "czerwonemu",
          acc: "czerwone",
          ins: "czerwonym",
          loc: "czerwonym",
        },
        f: {
          nom: "czerwona",
          gen: "czerwonej",
          dat: "czerwonej",
          acc: "czerwoną",
          ins: "czerwoną",
          loc: "czerwonej",
        },
      },
      plural: {
        virile: {
          nom: "czerwoni",
          gen: "czerwonych",
          dat: "czerwonym",
          acc: "czerwonych",
          ins: "czerwonymi",
          loc: "czerwonych",
        },
        nonvirile: {
          nom: "czerwone",
          gen: "czerwonych",
          dat: "czerwonym",
          acc: "czerwone",
          ins: "czerwonymi",
          loc: "czerwonych",
        },
      },
    },
  },
];
let adverbSet = [];
let verbSet = [];

exports.words = {
  nounSet,
  adjectiveSet,
  adverbSet,
  verbSet,
};
